##########################################
# Config du plugin UHPLUGIN              #
##########################################

map-size: 1000
# Distance entre 2 murs opposés 

pvp-disable: 60
# Temps de désactivation du PvP APRES le temps de disable des degats

damage-disable: 30

daylight-cycle: true

begin-storm: false
begin-time: 6000L

world: world