name: UHPlugin
main: me.zyuiop.uhplugin.UHPlugin
version: 1.0
author: zyuiop
commands:
    teams:
        description: Commandes d'équipes
        usage: /teams <ajouter|supprimer|lister> [nomteam]
        permission: uhpl.gameadmin
        permission-message: Permission manquante
    players:
        description: Commandes de joueurs
        usage: /players <ajouter|supprimer> [nomteam] [nomjoueur]
        permission: uhpl.gameadmin
        permission-message: Permission manquante
    gamestart:
        description: Démarre la partie UHC
        usage: /gamestart
        permission: uhpl.gameadmin
        permission-message: Permission manquante
    retrecir:
        description: Rétrecissement de la map de [taille]
        usage: /retrecir [taille]
        permission: uhpl.gameadmin
        permission-message: Permission manquante
    limites:
        description: Affiche les limites de la map
        usage: /limites
        permission: uhpl.joueur
        permission-message: Permission manquante
permissions:
    uhpl.gameadmin:
        default: op
        description: Permission de gestion de game
    uhpl.join:
        default: op
        description: Autorise le join si le jeu est lance
    uhpl.joueur:
        default: true
        description: Permissions joueur