name: OpenUHC
main: net.zyuiop.openUHC.OpenUHC
version: 0.9.1
authors: [zyuiop, Gnomino]
commands:
    teams:
        description: Teams management command
        usage: /teams add [teamname]
        permission: uhpl.gameadmin
        permission-message: Missing permission
    players:
        description: Players management commands
        usage: /players <add|delete> [nomteam] [nomjoueur]
        permission: uhpl.gameadmin
        permission-message: Missing permission
    gamestart:
        description: Startup the game
        usage: /gamestart
        permission: uhpl.gameadmin
        permission-message: Missing permission
    shrink:
        description: Reduce the size of the map by <size>
        usage: /shrink <size>
        permission: uhpl.gameadmin
        permission-message: Missing permission
    limits:
        description: Shows mao limits
        usage: /limites
        permission: uhpl.joueur
        permission-message: Permission manquante
permissions:
    uhpl.gameadmin:
        default: op
        description: Permission de gestion de game
    uhpl.join:
        default: op
        description: Autorise le join si le jeu est lance
    uhpl.joueur:
        default: true
        description: Permissions joueur
